### PR TITLE
feat: update navbar to the latest

### PR DESCRIPTION
**Pull request by guoqqqi**

### CODE REVIEW

**Comment by kayx23** [comment]
cr-gpt bot has been turned off

**Comment by kayx23** [comment]
@guoqqqi are you updating the doc top navbar in this PR as well? (the one currently says  Docs Home, Cloud, Apache APISIX)

Want to update `Cloud` to `API7 Cloud`; has been confirmed by @moonming

**Comment by guoqqqi** [comment]
@kayx23  No, I update this
image

**Comment by kayx23** [comment]
ok i'll open another PR

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
