### PR TITLE
feat: update docs Header

### PR DESCRIPTION
**Pull request by guoqqqi**

### CODE REVIEW

**Comment by juzhiyuan** [comment]
image


1. Be careful about the content style.
2. Unify content style and api7.ai

**Comment by juzhiyuan** [comment]
image

Does it look like you have resolved the Style conflict? Because Docusaurus is using full width, please keep the navbar aligned with Docusaurus.

**Comment by guoqqqi** [comment]
> Does it look like you have resolved the Style conflict?
I'm just using the chakra theme to fix the affected styles; as `swizzle` has many components, I'm checking if the interaction and style issues have an impact, and then I'll standardise the fonts, theme colours etc.

**Comment by guoqqqi** [comment]
Full width effect:
image

**Comment by juzhiyuan** [comment]
1. This button doesn't work on Chrome, Mac.

image

2. Please check the theme color with designer.

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
